Emulate gen_server:call/2 in java
Although the java-beamparticle node runs automatically,
but the following run starts another javanode
so that the logs are clearly visible.

    # ... run the release
    (beamparticle@127.0.0.1)1> gen_server:call({javaserver,
    'java@127.0.0.1'}, {'JavaClassName', 'JavaFunctionName', []}).
    {error,"java.lang.ClassNotFoundException: JavaClassName"}
    (beamparticle@127.0.0.1)2>
    (beamparticle@127.0.0.1)3> net_adm:names().
    {ok,[{"java-beamparticle",33997},{"beamparticle",9002}]}

    $ cd priv/javanode/bin
    $ ./javanode "java@127.0.0.1"
    "SomeCookie" "beamparticle@127.0.0.1" 1
    Java node launched with name=java@127.0.0.1
    Mailbox javaserver is listening...
    java.lang.ClassNotFoundException: JavaClassName
            at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
            at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
            at java.lang.Class.forName0(Native Method)
            at java.lang.Class.forName(Class.java:264)
            at
    com.beamparticle.JavaLambdaNode.<init>(JavaLambdaNode.java:73)
            at com.beamparticle.Application.main(Application.java:14)
    Mailbox javaserver is listening...